#ifndef _Register_atMB_
#define _Register_atMB_

/* _____DEFINETIONS__________________________________________________________ */


// Coils Register
enum LCM_DISCRETE_OUTPUT_COILS_REGISTER_FOR_NUMBER_DEVICES_INDEX
{
    LCM_DOC_REGISTER_RW_RDM_NUMBER = 10,
	LCM_DOC_REGISTER_RW_SNM_NUMBER,
	LCM_DOC_REGISTER_RW_IDM_NUMBER,
	LCM_DOC_REGISTER_RW_HDM_NUMBER,
	LCM_DOC_REGISTER_RW_EMM_NUMBER
};

enum LCM_DISCRETE_INPUT_CONTACTS_REGISTER_NUMBER_DEVICES_INDEX
{
    LCM_DIC_REGISTER_R_RDM_NUMBER = 10,
	LCM_DIC_REGISTER_R_SNM_NUMBER,
	LCM_DIC_REGISTER_R_IDM_NUMBER,
	LCM_DIC_REGISTER_R_HDM_NUMBER,
	LCM_DIC_REGISTER_R_EMM_NUMBER
};

enum LCM_HOLDING_REGISTERS_FOR_NUMBER_DEVICES_INDEX
{
    LCM_HR_REGISTER_RW_RDM_NUMBER = 10,
	LCM_HR_REGISTER_RW_SNM_NUMBER,
	LCM_HR_REGISTER_RW_IDM_NUMBER,
	LCM_HR_REGISTER_RW_HDM_NUMBER,
	LCM_HR_REGISTER_RW_EMM_NUMBER
};

enum LCM_INPUT_REGISTERS_FOR_NUMBER_DEVICES_INDEX
{
    LCM_IR_REGISTER_R_RDM_NUMBER = 10,
	LCM_IR_REGISTER_R_SNM_NUMBER,
	LCM_IR_REGISTER_R_IDM_NUMBER,
	LCM_IR_REGISTER_R_HDM_NUMBER,
	LCM_IR_REGISTER_R_EMM_NUMBER
};


#endif